import type { OnboardingTemplate } from './types';

export const TEMPLATES: OnboardingTemplate[] = [
  {
    id: 'pool-service',
    name: 'Pool Service',
    industry: 'Field Service',
    description: 'Automated scheduling, route optimization, chemical tracking, and customer communication for pool maintenance companies.',
    agents: [
      { name: 'Route Optimizer', role: 'Plans daily service routes for minimum drive time and maximum stops' },
      { name: 'Chemical Tracker', role: 'Monitors water chemistry readings and recommends treatments' },
      { name: 'Scheduling Agent', role: 'Handles recurring service schedules, cancellations, and rescheduling' },
      { name: 'Customer Comms Agent', role: 'Sends service reminders, completion reports, and follow-ups' },
      { name: 'Invoice Agent', role: 'Generates invoices after service completion and tracks payments' },
      { name: 'Equipment Monitor', role: 'Tracks pump, filter, and heater maintenance cycles' },
    ],
    workflows: [
      {
        name: 'Daily Service Dispatch',
        description: 'Morning route planning through service completion',
        steps: ['Pull schedule', 'Optimize routes', 'Dispatch techs', 'Log readings', 'Send reports'],
      },
      {
        name: 'New Customer Onboarding',
        description: 'Customer intake through first service',
        steps: ['Capture pool info', 'Set schedule', 'Initial assessment', 'Create billing'],
      },
      {
        name: 'Chemical Rebalance',
        description: 'Automated response to out-of-range readings',
        steps: ['Detect anomaly', 'Calculate treatment', 'Alert tech', 'Verify correction'],
      },
    ],
    strategies: ['route-optimized', 'cost-optimized', 'safe-mode'],
    systems: ['quickbooks', 'google-workspace', 'slack'],
    automationLevel: 'assisted',
    departments: [
      { name: 'Operations', enabled: true, level: 'autonomous' },
      { name: 'Scheduling', enabled: true, level: 'autonomous' },
      { name: 'Finance', enabled: true, level: 'assisted' },
      { name: 'Customer Service', enabled: true, level: 'assisted' },
    ],
    estimatedMinutes: 20,
  },
  {
    id: 'pest-control',
    name: 'Pest Control',
    industry: 'Field Service',
    description: 'Service scheduling, treatment tracking, regulatory compliance, and customer retention for pest management companies.',
    agents: [
      { name: 'Treatment Planner', role: 'Selects treatment protocols based on pest type, property, and season' },
      { name: 'Compliance Agent', role: 'Tracks pesticide usage, licensing, and regulatory documentation' },
      { name: 'Scheduling Agent', role: 'Manages recurring treatments, callbacks, and seasonal campaigns' },
      { name: 'Customer Retention Agent', role: 'Identifies at-risk accounts and triggers re-engagement workflows' },
      { name: 'Invoice Agent', role: 'Handles billing cycles, contract renewals, and payment follow-up' },
      { name: 'Inspection Reporter', role: 'Generates detailed inspection reports with photos and findings' },
    ],
    workflows: [
      {
        name: 'Service Call Workflow',
        description: 'From booking through treatment completion',
        steps: ['Receive request', 'Assess pest type', 'Assign tech', 'Apply treatment', 'Document results'],
      },
      {
        name: 'Quarterly Treatment Cycle',
        description: 'Recurring preventive treatment management',
        steps: ['Schedule reminders', 'Confirm appointments', 'Dispatch crew', 'Log chemicals', 'Invoice'],
      },
      {
        name: 'Compliance Audit',
        description: 'Regulatory documentation and reporting',
        steps: ['Gather usage logs', 'Verify licenses', 'Generate reports', 'Submit filings'],
      },
    ],
    strategies: ['compliance-first', 'balanced', 'safe-mode'],
    systems: ['quickbooks', 'google-workspace', 'slack'],
    automationLevel: 'assisted',
    departments: [
      { name: 'Operations', enabled: true, level: 'assisted' },
      { name: 'Scheduling', enabled: true, level: 'autonomous' },
      { name: 'Compliance', enabled: true, level: 'approval' },
      { name: 'Finance', enabled: true, level: 'assisted' },
      { name: 'Customer Service', enabled: true, level: 'assisted' },
    ],
    estimatedMinutes: 25,
  },
  {
    id: 'landscaping',
    name: 'Landscaping',
    industry: 'Field Service',
    description: 'Crew scheduling, job costing, seasonal planning, and property management for landscaping and lawn care businesses.',
    agents: [
      { name: 'Crew Scheduler', role: 'Assigns crews to jobs based on skills, equipment, and location' },
      { name: 'Job Estimator', role: 'Generates quotes from property size, service type, and material costs' },
      { name: 'Route Optimizer', role: 'Plans efficient daily routes across multiple job sites' },
      { name: 'Weather Monitor', role: 'Tracks forecasts and auto-reschedules weather-sensitive work' },
      { name: 'Invoice Agent', role: 'Calculates job costs, generates invoices, and tracks receivables' },
      { name: 'Seasonal Planner', role: 'Plans spring/fall cleanups, aeration, and seasonal service shifts' },
    ],
    workflows: [
      {
        name: 'Daily Crew Dispatch',
        description: 'Morning planning through end-of-day reporting',
        steps: ['Check weather', 'Assign crews', 'Optimize routes', 'Track progress', 'Close out jobs'],
      },
      {
        name: 'New Property Estimate',
        description: 'Lead intake through proposal delivery',
        steps: ['Site assessment', 'Measure property', 'Calculate materials', 'Generate quote', 'Send proposal'],
      },
      {
        name: 'Seasonal Transition',
        description: 'Service mix changes between seasons',
        steps: ['Analyze calendar', 'Update service offerings', 'Notify customers', 'Adjust schedules'],
      },
    ],
    strategies: ['route-optimized', 'cost-optimized', 'balanced'],
    systems: ['quickbooks', 'google-workspace', 'slack'],
    automationLevel: 'assisted',
    departments: [
      { name: 'Operations', enabled: true, level: 'autonomous' },
      { name: 'Scheduling', enabled: true, level: 'autonomous' },
      { name: 'Sales', enabled: true, level: 'assisted' },
      { name: 'Finance', enabled: true, level: 'assisted' },
    ],
    estimatedMinutes: 20,
  },
  {
    id: 'manufacturing',
    name: 'Manufacturing Operations',
    industry: 'Manufacturing',
    description: 'Cross-system production coordination, quality management, maintenance optimization, and supply chain visibility for discrete and process manufacturers.',
    agents: [
      { name: 'Production-ERP Sync', role: 'Monitors discrepancies between ERP planned orders and MES actual production, flags mismatches within 15 minutes' },
      { name: 'Quality Hold Propagation', role: 'When quality issues are detected, automatically notifies scheduling, shipping, and procurement to prevent downstream impact' },
      { name: 'Shift Handoff Coordinator', role: 'Compiles end-of-shift status across all systems and generates structured handoff briefs for incoming supervisors' },
      { name: 'Maintenance Window Optimizer', role: 'Analyzes production schedules and equipment sensor data to recommend maintenance windows that minimize throughput impact' },
      { name: 'Material Availability Monitor', role: 'Tracks raw material levels across warehouse and shop floor, predicts stockouts 48-72 hours ahead, triggers procurement alerts' },
      { name: 'Downtime Root Cause Analyzer', role: 'Correlates equipment logs, quality data, and operator inputs to identify root causes of unplanned downtime events' },
      { name: 'Schedule Adherence Tracker', role: 'Compares planned production schedule against actual progress, calculates adherence percentage, alerts on drift beyond threshold' },
      { name: 'Supplier Performance Monitor', role: 'Tracks on-time delivery, quality rejection rates, and lead time trends per supplier across all incoming materials' },
    ],
    workflows: [
      {
        name: 'Daily Production Dispatch',
        description: 'Morning planning through end-of-shift closeout',
        steps: ['Pull ERP orders', 'Verify material availability', 'Generate production schedule', 'Assign to lines', 'Monitor execution', 'Quality gate check', 'Shift closeout report'],
      },
      {
        name: 'Quality Escape Response',
        description: 'Containment and correction when defective product is detected downstream',
        steps: ['Detect quality event', 'Quarantine affected lots', 'Trace back to root cause', 'Notify affected parties', 'Generate CAPA', 'Verify correction', 'Release hold'],
      },
      {
        name: 'Preventive Maintenance Coordination',
        description: 'Predictive scheduling and execution of equipment maintenance',
        steps: ['Analyze sensor trends', 'Predict failure window', 'Check parts availability', 'Schedule maintenance window', 'Coordinate with production', 'Execute maintenance', 'Verify equipment health'],
      },
      {
        name: 'Supplier Disruption Response',
        description: 'Rapid response when a critical supplier misses delivery or quality targets',
        steps: ['Detect delivery exception', 'Assess production impact', 'Identify alternate sources', 'Adjust production schedule', 'Notify customers if needed', 'Track resolution'],
      },
    ],
    strategies: ['throughput-optimized', 'quality-first', 'balanced', 'safe-mode'],
    systems: ['erp', 'microsoft365', 'slack', 'quickbooks'],
    automationLevel: 'assisted',
    departments: [
      { name: 'Production', enabled: true, level: 'assisted' },
      { name: 'Quality', enabled: true, level: 'approval' },
      { name: 'Maintenance', enabled: true, level: 'assisted' },
      { name: 'Supply Chain', enabled: true, level: 'assisted' },
      { name: 'Scheduling', enabled: true, level: 'autonomous' },
      { name: 'Shipping & Logistics', enabled: true, level: 'assisted' },
      { name: 'Finance', enabled: true, level: 'approval' },
    ],
    estimatedMinutes: 30,
    complianceNotes: [
      { standard: 'ISO 9001', status: 'enabled', description: 'Quality audit trail via immutable SHA-256 hash-chained audit log' },
      { standard: 'FDA 21 CFR Part 11', status: 'available', description: 'Electronic signatures, audit trail, access controls' },
      { standard: 'OSHA Incident Correlation', status: 'available', description: 'Exception intelligence tracks safety-relevant patterns' },
    ],
    trustTierDefaults: [
      { actionScope: 'production.schedule', maxTier: 'T3', rationale: 'Scheduling changes are reversible and time-sensitive' },
      { actionScope: 'quality.hold', maxTier: 'T1', rationale: 'Quality holds have regulatory implications' },
      { actionScope: 'maintenance.schedule', maxTier: 'T3', rationale: 'Maintenance windows are reschedulable' },
      { actionScope: 'procurement.order', maxTier: 'T2', rationale: 'Purchase orders require financial approval' },
      { actionScope: 'shipping.release', maxTier: 'T2', rationale: 'Shipment releases need quality verification' },
      { actionScope: 'quality.disposition', maxTier: 'T1', rationale: 'Material disposition requires quality engineer sign-off' },
      { actionScope: 'supplier.escalation', maxTier: 'T2', rationale: 'Supplier escalations should be reviewed before sending' },
    ],
    shadowScenarios: [
      {
        title: 'Quality Hold Not Communicated',
        problem: 'A quality hold was placed on a batch, but the shipping department was not notified and shipped 3 pallets of affected product.',
        detection: 'Quality Hold Propagation agent detects hold event and cross-references open shipping orders within 2 minutes.',
        action: 'Automatically flags affected shipments, notifies shipping supervisor, and places temporary hold on related orders.',
        savings: '$47,000 rework saved',
      },
      {
        title: 'Material Stockout Surprise',
        problem: 'A critical raw material ran out mid-shift because inventory counts were stale, halting a production line for 6 hours.',
        detection: 'Material Availability Monitor predicts stockout 48-72 hours ahead by correlating consumption rates with on-hand inventory.',
        action: 'Triggers procurement alert and suggests alternate sourcing or schedule adjustment before stockout occurs.',
        savings: '$28,000 lost production saved',
      },
      {
        title: 'Shift Handoff Gap',
        problem: 'Incoming shift was unaware of a machine running out of spec, producing 4 hours of defective product before detection.',
        detection: 'Shift Handoff Coordinator compiles machine status, active alerts, and quality flags into structured brief.',
        action: 'Generates handoff brief highlighting out-of-spec condition, ensuring incoming supervisor addresses it immediately.',
        savings: '4 hours out-of-spec production prevented',
      },
    ],
  },
];
