import type { OnboardingTemplate } from './types';

export const TEMPLATES: OnboardingTemplate[] = [
  {
    id: 'pool-service',
    name: 'Pool Service',
    industry: 'Field Service',
    description: 'Automated scheduling, route optimization, chemical tracking, and customer communication for pool maintenance companies.',
    agents: [
      { name: 'Route Optimizer', role: 'Plans daily service routes for minimum drive time and maximum stops' },
      { name: 'Chemical Tracker', role: 'Monitors water chemistry readings and recommends treatments' },
      { name: 'Scheduling Agent', role: 'Handles recurring service schedules, cancellations, and rescheduling' },
      { name: 'Customer Comms Agent', role: 'Sends service reminders, completion reports, and follow-ups' },
      { name: 'Invoice Agent', role: 'Generates invoices after service completion and tracks payments' },
      { name: 'Equipment Monitor', role: 'Tracks pump, filter, and heater maintenance cycles' },
    ],
    workflows: [
      {
        name: 'Daily Service Dispatch',
        description: 'Morning route planning through service completion',
        steps: ['Pull schedule', 'Optimize routes', 'Dispatch techs', 'Log readings', 'Send reports'],
      },
      {
        name: 'New Customer Onboarding',
        description: 'Customer intake through first service',
        steps: ['Capture pool info', 'Set schedule', 'Initial assessment', 'Create billing'],
      },
      {
        name: 'Chemical Rebalance',
        description: 'Automated response to out-of-range readings',
        steps: ['Detect anomaly', 'Calculate treatment', 'Alert tech', 'Verify correction'],
      },
    ],
    strategies: ['route-optimized', 'cost-optimized', 'safe-mode'],
    systems: ['quickbooks', 'google-workspace', 'slack'],
    automationLevel: 'assisted',
    departments: [
      { name: 'Operations', enabled: true, level: 'autonomous' },
      { name: 'Scheduling', enabled: true, level: 'autonomous' },
      { name: 'Finance', enabled: true, level: 'assisted' },
      { name: 'Customer Service', enabled: true, level: 'assisted' },
    ],
    estimatedMinutes: 20,
  },
  {
    id: 'pest-control',
    name: 'Pest Control',
    industry: 'Field Service',
    description: 'Service scheduling, treatment tracking, regulatory compliance, and customer retention for pest management companies.',
    agents: [
      { name: 'Treatment Planner', role: 'Selects treatment protocols based on pest type, property, and season' },
      { name: 'Compliance Agent', role: 'Tracks pesticide usage, licensing, and regulatory documentation' },
      { name: 'Scheduling Agent', role: 'Manages recurring treatments, callbacks, and seasonal campaigns' },
      { name: 'Customer Retention Agent', role: 'Identifies at-risk accounts and triggers re-engagement workflows' },
      { name: 'Invoice Agent', role: 'Handles billing cycles, contract renewals, and payment follow-up' },
      { name: 'Inspection Reporter', role: 'Generates detailed inspection reports with photos and findings' },
    ],
    workflows: [
      {
        name: 'Service Call Workflow',
        description: 'From booking through treatment completion',
        steps: ['Receive request', 'Assess pest type', 'Assign tech', 'Apply treatment', 'Document results'],
      },
      {
        name: 'Quarterly Treatment Cycle',
        description: 'Recurring preventive treatment management',
        steps: ['Schedule reminders', 'Confirm appointments', 'Dispatch crew', 'Log chemicals', 'Invoice'],
      },
      {
        name: 'Compliance Audit',
        description: 'Regulatory documentation and reporting',
        steps: ['Gather usage logs', 'Verify licenses', 'Generate reports', 'Submit filings'],
      },
    ],
    strategies: ['compliance-first', 'balanced', 'safe-mode'],
    systems: ['quickbooks', 'google-workspace', 'slack'],
    automationLevel: 'assisted',
    departments: [
      { name: 'Operations', enabled: true, level: 'assisted' },
      { name: 'Scheduling', enabled: true, level: 'autonomous' },
      { name: 'Compliance', enabled: true, level: 'approval' },
      { name: 'Finance', enabled: true, level: 'assisted' },
      { name: 'Customer Service', enabled: true, level: 'assisted' },
    ],
    estimatedMinutes: 25,
  },
  {
    id: 'landscaping',
    name: 'Landscaping',
    industry: 'Field Service',
    description: 'Crew scheduling, job costing, seasonal planning, and property management for landscaping and lawn care businesses.',
    agents: [
      { name: 'Crew Scheduler', role: 'Assigns crews to jobs based on skills, equipment, and location' },
      { name: 'Job Estimator', role: 'Generates quotes from property size, service type, and material costs' },
      { name: 'Route Optimizer', role: 'Plans efficient daily routes across multiple job sites' },
      { name: 'Weather Monitor', role: 'Tracks forecasts and auto-reschedules weather-sensitive work' },
      { name: 'Invoice Agent', role: 'Calculates job costs, generates invoices, and tracks receivables' },
      { name: 'Seasonal Planner', role: 'Plans spring/fall cleanups, aeration, and seasonal service shifts' },
    ],
    workflows: [
      {
        name: 'Daily Crew Dispatch',
        description: 'Morning planning through end-of-day reporting',
        steps: ['Check weather', 'Assign crews', 'Optimize routes', 'Track progress', 'Close out jobs'],
      },
      {
        name: 'New Property Estimate',
        description: 'Lead intake through proposal delivery',
        steps: ['Site assessment', 'Measure property', 'Calculate materials', 'Generate quote', 'Send proposal'],
      },
      {
        name: 'Seasonal Transition',
        description: 'Service mix changes between seasons',
        steps: ['Analyze calendar', 'Update service offerings', 'Notify customers', 'Adjust schedules'],
      },
    ],
    strategies: ['route-optimized', 'cost-optimized', 'balanced'],
    systems: ['quickbooks', 'google-workspace', 'slack'],
    automationLevel: 'assisted',
    departments: [
      { name: 'Operations', enabled: true, level: 'autonomous' },
      { name: 'Scheduling', enabled: true, level: 'autonomous' },
      { name: 'Sales', enabled: true, level: 'assisted' },
      { name: 'Finance', enabled: true, level: 'assisted' },
    ],
    estimatedMinutes: 20,
  },
  {
    id: 'manufacturing',
    name: 'Manufacturing Operations',
    industry: 'Manufacturing',
    description: 'Cross-system production coordination, quality management, maintenance optimization, and supply chain visibility for discrete and process manufacturers.',
    agents: [
      { name: 'Production-ERP Sync', role: 'Monitors discrepancies between ERP planned orders and MES actual production, flags mismatches within 15 minutes' },
      { name: 'Quality Hold Propagation', role: 'When quality issues are detected, automatically notifies scheduling, shipping, and procurement to prevent downstream impact' },
      { name: 'Shift Handoff Coordinator', role: 'Compiles end-of-shift status across all systems and generates structured handoff briefs for incoming supervisors' },
      { name: 'Maintenance Window Optimizer', role: 'Analyzes production schedules and equipment sensor data to recommend maintenance windows that minimize throughput impact' },
      { name: 'Material Availability Monitor', role: 'Tracks raw material levels across warehouse and shop floor, predicts stockouts 48-72 hours ahead, triggers procurement alerts' },
      { name: 'Downtime Root Cause Analyzer', role: 'Correlates equipment logs, quality data, and operator inputs to identify root causes of unplanned downtime events' },
      { name: 'Schedule Adherence Tracker', role: 'Compares planned production schedule against actual progress, calculates adherence percentage, alerts on drift beyond threshold' },
      { name: 'Supplier Performance Monitor', role: 'Tracks on-time delivery, quality rejection rates, and lead time trends per supplier across all incoming materials' },
    ],
    workflows: [
      {
        name: 'Daily Production Dispatch',
        description: 'Morning planning through end-of-shift closeout',
        steps: ['Pull ERP orders', 'Verify material availability', 'Generate production schedule', 'Assign to lines', 'Monitor execution', 'Quality gate check', 'Shift closeout report'],
      },
      {
        name: 'Quality Escape Response',
        description: 'Containment and correction when defective product is detected downstream',
        steps: ['Detect quality event', 'Quarantine affected lots', 'Trace back to root cause', 'Notify affected parties', 'Generate CAPA', 'Verify correction', 'Release hold'],
      },
      {
        name: 'Preventive Maintenance Coordination',
        description: 'Predictive scheduling and execution of equipment maintenance',
        steps: ['Analyze sensor trends', 'Predict failure window', 'Check parts availability', 'Schedule maintenance window', 'Coordinate with production', 'Execute maintenance', 'Verify equipment health'],
      },
      {
        name: 'Supplier Disruption Response',
        description: 'Rapid response when a critical supplier misses delivery or quality targets',
        steps: ['Detect delivery exception', 'Assess production impact', 'Identify alternate sources', 'Adjust production schedule', 'Notify customers if needed', 'Track resolution'],
      },
    ],
    strategies: ['throughput-optimized', 'quality-first', 'balanced', 'safe-mode'],
    systems: ['erp', 'microsoft365', 'slack', 'quickbooks'],
    automationLevel: 'assisted',
    departments: [
      { name: 'Production', enabled: true, level: 'assisted' },
      { name: 'Quality', enabled: true, level: 'approval' },
      { name: 'Maintenance', enabled: true, level: 'assisted' },
      { name: 'Supply Chain', enabled: true, level: 'assisted' },
      { name: 'Scheduling', enabled: true, level: 'autonomous' },
      { name: 'Shipping & Logistics', enabled: true, level: 'assisted' },
      { name: 'Finance', enabled: true, level: 'approval' },
    ],
    estimatedMinutes: 30,
    complianceNotes: [
      { standard: 'ISO 9001', status: 'enabled', description: 'Quality audit trail via immutable SHA-256 hash-chained audit log' },
      { standard: 'FDA 21 CFR Part 11', status: 'available', description: 'Electronic signatures, audit trail, access controls' },
      { standard: 'OSHA Incident Correlation', status: 'available', description: 'Exception intelligence tracks safety-relevant patterns' },
    ],
    trustTierDefaults: [
      { actionScope: 'production.schedule', maxTier: 'T3', rationale: 'Scheduling changes are reversible and time-sensitive' },
      { actionScope: 'quality.hold', maxTier: 'T1', rationale: 'Quality holds have regulatory implications' },
      { actionScope: 'maintenance.schedule', maxTier: 'T3', rationale: 'Maintenance windows are reschedulable' },
      { actionScope: 'procurement.order', maxTier: 'T2', rationale: 'Purchase orders require financial approval' },
      { actionScope: 'shipping.release', maxTier: 'T2', rationale: 'Shipment releases need quality verification' },
      { actionScope: 'quality.disposition', maxTier: 'T1', rationale: 'Material disposition requires quality engineer sign-off' },
      { actionScope: 'supplier.escalation', maxTier: 'T2', rationale: 'Supplier escalations should be reviewed before sending' },
    ],
    shadowScenarios: [
      {
        title: 'Quality Hold Not Communicated',
        problem: 'A quality hold was placed on a batch, but the shipping department was not notified and shipped 3 pallets of affected product.',
        detection: 'Quality Hold Propagation agent detects hold event and cross-references open shipping orders within 2 minutes.',
        action: 'Automatically flags affected shipments, notifies shipping supervisor, and places temporary hold on related orders.',
        savings: '$47,000 rework saved',
      },
      {
        title: 'Material Stockout Surprise',
        problem: 'A critical raw material ran out mid-shift because inventory counts were stale, halting a production line for 6 hours.',
        detection: 'Material Availability Monitor predicts stockout 48-72 hours ahead by correlating consumption rates with on-hand inventory.',
        action: 'Triggers procurement alert and suggests alternate sourcing or schedule adjustment before stockout occurs.',
        savings: '$28,000 lost production saved',
      },
      {
        title: 'Shift Handoff Gap',
        problem: 'Incoming shift was unaware of a machine running out of spec, producing 4 hours of defective product before detection.',
        detection: 'Shift Handoff Coordinator compiles machine status, active alerts, and quality flags into structured brief.',
        action: 'Generates handoff brief highlighting out-of-spec condition, ensuring incoming supervisor addresses it immediately.',
        savings: '4 hours out-of-spec production prevented',
      },
    ],
  },
  {
    id: 'healthcare',
    name: 'Healthcare Operations',
    industry: 'Healthcare',
    description: 'Patient flow coordination, revenue cycle optimization, compliance management, and care transition orchestration for hospitals, clinics, and health systems.',
    agents: [
      { name: 'Patient Flow Coordinator', role: 'Manages bed assignments, discharge planning, and transfer coordination across departments to reduce wait times and improve throughput' },
      { name: 'Prior Authorization Tracker', role: 'Monitors authorization submissions, follows up on pending approvals, escalates delays, and links approvals to scheduling' },
      { name: 'Revenue Cycle Exception Handler', role: 'Identifies denied claims, coding errors, and payment posting exceptions; recommends corrections and tracks rework' },
      { name: 'Care Transition Orchestrator', role: 'Manages referral workflows, ensures handoff documentation is complete, schedules follow-ups, and tracks transitions between care settings' },
      { name: 'Staff Scheduling Optimizer', role: 'Matches staff credentials to department needs, optimizes shift coverage, predicts overtime exposure, and handles swap requests' },
      { name: 'Compliance & Audit Monitor', role: 'Tracks HIPAA access patterns, consent documentation, incident reports, and generates compliance audit readiness summaries' },
      { name: 'Clinical Documentation Integrity Agent', role: 'Reviews documentation for completeness, identifies coding opportunities, flags inconsistencies before claim submission' },
      { name: 'Patient Communication Agent', role: 'Manages appointment reminders, pre-visit instructions, post-visit follow-ups, and satisfaction surveys across channels' },
    ],
    workflows: [
      {
        name: 'Prior Authorization Pipeline',
        description: 'From order entry through authorization to scheduling',
        steps: ['Receive order', 'Check payer requirements', 'Submit authorization', 'Track status', 'Escalate delays', 'Link to scheduling', 'Document outcome'],
      },
      {
        name: 'Patient Discharge Coordination',
        description: 'Coordinated discharge from readiness through follow-up',
        steps: ['Assess discharge readiness', 'Coordinate transport', 'Prepare medications', 'Complete documentation', 'Notify PCP', 'Schedule follow-up', 'Post-discharge check-in'],
      },
      {
        name: 'Denied Claim Recovery',
        description: 'Systematic rework of denied insurance claims',
        steps: ['Identify denial', 'Classify denial reason', 'Pull supporting documentation', 'Correct and resubmit', 'Track appeal', 'Update patient account', 'Report recovery metrics'],
      },
      {
        name: 'New Patient Onboarding',
        description: 'Complete patient intake and system setup',
        steps: ['Collect demographics', 'Verify insurance', 'Check prior authorizations', 'Schedule first appointment', 'Send welcome packet', 'Complete intake forms'],
      },
    ],
    strategies: ['patient-safety-first', 'throughput-optimized', 'compliance-first', 'balanced'],
    systems: ['microsoft365', 'slack', 'quickbooks'],
    automationLevel: 'approval',
    departments: [
      { name: 'Patient Access', enabled: true, level: 'assisted' },
      { name: 'Clinical Operations', enabled: true, level: 'approval' },
      { name: 'Revenue Cycle', enabled: true, level: 'assisted' },
      { name: 'Scheduling', enabled: true, level: 'assisted' },
      { name: 'Compliance', enabled: true, level: 'approval' },
      { name: 'Nursing Administration', enabled: true, level: 'approval' },
      { name: 'IT / Health Informatics', enabled: true, level: 'assisted' },
      { name: 'Finance', enabled: true, level: 'approval' },
    ],
    complianceNotes: [
      { standard: 'HIPAA Privacy Rule', status: 'enabled', description: 'All data access logged to immutable audit trail. Role-based access controls enforce minimum necessary access.' },
      { standard: 'HIPAA Security Rule', status: 'enabled', description: 'AES-256 encryption at rest, TLS in transit. Dedicated TOTP encryption key. Multi-factor authentication available.' },
      { standard: 'HIPAA Audit Requirements', status: 'enabled', description: 'SHA-256 hash-chained audit trail with integrity verification. All agent actions recorded with full lineage.' },
      { standard: 'HITECH Breach Notification', status: 'available', description: 'Exception intelligence can detect unusual access patterns. Incident reporting workflows configurable.' },
      { standard: '21st Century Cures Act', status: 'available', description: 'FHIR-compatible connector framework supports Health IT interoperability requirements.' },
    ],
    trustTierDefaults: [
      { actionScope: 'patient.scheduling', maxTier: 'T2', rationale: 'Patient scheduling changes require clinical review' },
      { actionScope: 'patient.communication', maxTier: 'T3', rationale: 'Appointment reminders and standard communications are reversible' },
      { actionScope: 'clinical.documentation', maxTier: 'T1', rationale: 'Clinical documentation changes require physician review' },
      { actionScope: 'billing.claim-submission', maxTier: 'T2', rationale: 'Claim submissions require coding review before sending' },
      { actionScope: 'billing.adjustment', maxTier: 'T1', rationale: 'Financial adjustments require supervisor approval' },
      { actionScope: 'compliance.reporting', maxTier: 'T2', rationale: 'Compliance reports require review before submission' },
      { actionScope: 'staffing.schedule', maxTier: 'T3', rationale: 'Staff scheduling changes are reversible and time-sensitive' },
      { actionScope: 'patient.data-access', maxTier: 'T0', rationale: 'PHI access is observe-only by default; explicit authorization required' },
    ],
    shadowScenarios: [
      {
        title: 'Authorization Delay Cascade',
        problem: 'Prior auth for MRI sat pending 9 days with no follow-up. Patient condition worsened, requiring ER visit ($4,200).',
        detection: 'Prior Authorization Tracker would have escalated at 48 hours.',
        action: 'Automatic escalation to payer liaison and scheduling notification upon delay threshold.',
        savings: '$4,200 + 7 days delay avoided',
      },
      {
        title: 'Denied Claim Batch',
        problem: '47 claims denied for same coding error over 3 weeks before pattern noticed. Total: $128,000.',
        detection: 'Revenue Cycle Exception Handler detects pattern after 3rd denial.',
        action: 'Flags coding error pattern, halts similar submissions, and queues bulk correction.',
        savings: '$128,000 recovered in 2 days vs 6 weeks',
      },
      {
        title: 'Discharge Coordination Gap',
        problem: 'Patient medically ready at 10am, discharged 4pm due to phone-tag coordination.',
        detection: 'Care Transition Orchestrator coordinates all parties simultaneously.',
        action: 'Parallel notification to transport, pharmacy, PCP, and follow-up scheduling.',
        savings: '6 bed-hours recovered per incident',
      },
    ],
    estimatedMinutes: 35,
  },
  {
    id: 'financial-services',
    name: 'Financial Services Operations',
    industry: 'Financial Services',
    description: 'Transaction surveillance, regulatory reporting, portfolio monitoring, operational risk management, and client lifecycle automation for banks, asset managers, and financial institutions.',
    agents: [
      { name: 'Transaction Surveillance Agent', role: 'Monitors transaction patterns for suspicious activity, generates SAR filing recommendations, tracks investigation workflows' },
      { name: 'Regulatory Reporting Coordinator', role: 'Automates SOX, MiFID II, Dodd-Frank, and Basel III reporting cycles; tracks deadlines, gathers data, flags gaps' },
      { name: 'Portfolio Drift Monitor', role: 'Detects allocation drift from investment policy, triggers rebalancing recommendations, calculates tracking error' },
      { name: 'Credit Risk Assessor', role: 'Scores applications against credit policies, monitors exposure limits, generates early warning signals on deteriorating credits' },
      { name: 'Operational Risk Tracker', role: 'Logs risk events, tracks control testing, monitors loss events, generates risk committee summaries' },
      { name: 'KYC/AML Compliance Agent', role: 'Manages identity verification workflows, sanctions screening, enhanced due diligence triggers, periodic review scheduling' },
      { name: 'Client Lifecycle Manager', role: 'Orchestrates onboarding, account reviews, document collection, and offboarding workflows across client relationships' },
      { name: 'Reconciliation Agent', role: 'Matches transactions across systems, identifies breaks, escalates unresolved items, tracks aging of open breaks' },
    ],
    workflows: [
      {
        name: 'Client Onboarding Pipeline',
        description: 'Complete client intake through account activation',
        steps: ['KYC collection', 'Identity verification', 'Sanctions screening', 'Account opening', 'Product suitability', 'Documentation', 'Welcome'],
      },
      {
        name: 'Regulatory Filing Cycle',
        description: 'Periodic regulatory report preparation and submission',
        steps: ['Data gathering', 'Validation', 'Review', 'Submission', 'Confirmation', 'Archive'],
      },
      {
        name: 'Suspicious Activity Escalation',
        description: 'From pattern detection through SAR filing',
        steps: ['Pattern detection', 'Alert generation', 'Investigation assignment', 'Evidence collection', 'SAR filing decision', 'Regulatory submission'],
      },
      {
        name: 'End-of-Day Reconciliation',
        description: 'Cross-system position matching and exception handling',
        steps: ['Extract positions', 'Match across systems', 'Identify breaks', 'Classify exceptions', 'Escalate unresolved', 'Generate exception report'],
      },
    ],
    strategies: ['compliance-first', 'risk-adjusted', 'balanced', 'safe-mode'],
    systems: ['erp', 'microsoft365', 'quickbooks', 'salesforce'],
    automationLevel: 'approval',
    departments: [
      { name: 'Trading Operations', enabled: true, level: 'approval' },
      { name: 'Risk Management', enabled: true, level: 'approval' },
      { name: 'Compliance', enabled: true, level: 'approval' },
      { name: 'Client Services', enabled: true, level: 'assisted' },
      { name: 'Finance & Accounting', enabled: true, level: 'approval' },
      { name: 'IT & Security', enabled: true, level: 'assisted' },
      { name: 'Reporting', enabled: true, level: 'assisted' },
    ],
    complianceNotes: [
      { standard: 'SOX Compliance', status: 'enabled', description: 'Hash-chained audit trail provides tamper-evident record of all system actions and approvals' },
      { standard: 'MiFID II Best Execution', status: 'available', description: 'Proof analytics track decision-to-outcome lineage for best execution documentation' },
      { standard: 'Basel III Operational Risk', status: 'available', description: 'Exception intelligence and economic impact tracking support operational risk reporting' },
      { standard: 'GDPR Data Subject Rights', status: 'enabled', description: 'Article 15/17/20 data subject request workflows built in with erasure certificates' },
      { standard: 'AML/KYC Regulations', status: 'available', description: 'Approval gates enforce four-eyes review; separation of duties prevents self-approval' },
    ],
    trustTierDefaults: [
      { actionScope: 'trading.execution', maxTier: 'T1', rationale: 'Trade execution requires human authorization' },
      { actionScope: 'risk.assessment', maxTier: 'T2', rationale: 'Risk assessments need review before distribution' },
      { actionScope: 'compliance.filing', maxTier: 'T2', rationale: 'Regulatory filings require compliance officer sign-off' },
      { actionScope: 'client.communication', maxTier: 'T3', rationale: 'Standard client communications are reversible' },
      { actionScope: 'reconciliation.matching', maxTier: 'T3', rationale: 'Auto-matching confirmed transactions is safe and reversible' },
      { actionScope: 'client.onboarding', maxTier: 'T2', rationale: 'New client accounts require compliance review' },
      { actionScope: 'reporting.generation', maxTier: 'T3', rationale: 'Internal reports are reversible; distribution requires approval' },
      { actionScope: 'aml.screening', maxTier: 'T2', rationale: 'Screening results require compliance analyst review' },
    ],
    shadowScenarios: [
      {
        title: 'Reconciliation Break Undetected',
        problem: '$2.3M position break between trading system and custodian unnoticed for 5 business days. Manual rec checked weekly.',
        detection: 'Reconciliation Agent would flag within 4 hours.',
        action: 'Automatic break detection with escalation to operations and risk management.',
        savings: 'Risk avoided: failed settlement + regulatory error',
      },
      {
        title: 'SAR Filing Deadline Missed',
        problem: 'Suspicious patterns across 3 accounts identified but 30-day SAR filing deadline missed due to manual tracking.',
        detection: 'Transaction Surveillance Agent auto-tracks timelines and escalates at day 20.',
        action: 'Automated deadline tracking with escalation workflow and compliance officer notification.',
        savings: 'Risk avoided: $50K-$1M regulatory penalty per violation',
      },
      {
        title: 'Client Onboarding Stall',
        problem: 'High-value prospect onboarding took 47 days due to document handoffs between 4 departments.',
        detection: 'Client Lifecycle Manager orchestrates parallel workstreams and escalates stalls at 48 hours.',
        action: 'Parallel document collection, automated status tracking, and escalation at configurable thresholds.',
        savings: 'Improvement: 47 days → 12 days',
      },
    ],
    estimatedMinutes: 30,
  },
  {
    id: 'energy',
    name: 'Energy & Utilities Operations',
    industry: 'Energy',
    description: 'Asset performance monitoring, outage response coordination, regulatory compliance, grid operations, and safety management for power generation, transmission, distribution, and oil & gas.',
    agents: [
      { name: 'Asset Performance Monitor', role: 'Tracks equipment health scores from sensor data, predicts degradation curves, recommends maintenance before failure' },
      { name: 'Outage Response Coordinator', role: 'Detects outage events, classifies severity, coordinates dispatch crews, tracks restoration, generates post-event reports' },
      { name: 'Regulatory Compliance Tracker', role: 'Monitors NERC CIP, EPA, FERC, and state PUC requirements; tracks filing deadlines; flags compliance gaps' },
      { name: 'Energy Market Monitor', role: 'Tracks wholesale prices, demand forecasts, and generation costs; recommends dispatch and procurement decisions' },
      { name: 'Grid Load Balancer', role: 'Monitors real-time load across feeders, predicts demand spikes, recommends load shedding or generation dispatch' },
      { name: 'Safety Incident Correlator', role: 'Analyzes near-miss reports, safety observations, and incident data to identify systemic patterns before injuries occur' },
      { name: 'Environmental Compliance Agent', role: 'Tracks emissions data, monitors environmental permits, generates EPA and state regulatory filings' },
      { name: 'Field Crew Optimizer', role: 'Assigns field crews to work orders based on skills, certifications, location, and equipment availability' },
    ],
    workflows: [
      {
        name: 'Planned Maintenance Coordination',
        description: 'From assessment through closeout',
        steps: ['Asset assessment', 'Work order generation', 'Parts verification', 'Crew scheduling', 'Safety briefing', 'Execution', 'Verification', 'Closeout'],
      },
      {
        name: 'Unplanned Outage Response',
        description: 'Detection through restoration and reporting',
        steps: ['Detection', 'Classification', 'Crew dispatch', 'Isolation', 'Repair', 'Restoration', 'Customer notification', 'Post-event report'],
      },
      {
        name: 'Regulatory Filing Pipeline',
        description: 'Periodic compliance report preparation',
        steps: ['Data collection', 'Validation', 'Internal review', 'Submission', 'Confirmation tracking', 'Archive'],
      },
      {
        name: 'Safety Investigation',
        description: 'From incident through corrective action',
        steps: ['Incident report', 'Initial assessment', 'Root cause analysis', 'Corrective action plan', 'Implementation', 'Verification', 'Closure'],
      },
    ],
    strategies: ['safety-first', 'reliability-optimized', 'balanced', 'safe-mode'],
    systems: ['microsoft365', 'slack'],
    automationLevel: 'approval',
    departments: [
      { name: 'Generation', enabled: true, level: 'approval' },
      { name: 'Transmission & Distribution', enabled: true, level: 'approval' },
      { name: 'Field Operations', enabled: true, level: 'assisted' },
      { name: 'Safety & Compliance', enabled: true, level: 'approval' },
      { name: 'Environmental', enabled: true, level: 'approval' },
      { name: 'Grid Operations', enabled: true, level: 'approval' },
      { name: 'Finance', enabled: true, level: 'approval' },
      { name: 'Customer Operations', enabled: true, level: 'assisted' },
    ],
    complianceNotes: [
      { standard: 'NERC CIP', status: 'available', description: 'Critical infrastructure protection: role-based access, audit trails, change management tracking' },
      { standard: 'EPA Reporting', status: 'available', description: 'Environmental compliance data collection and filing workflow support' },
      { standard: 'FERC Standards', status: 'available', description: 'Reliability standard compliance tracking and evidence management' },
      { standard: 'OSHA Process Safety', status: 'available', description: 'Safety incident tracking, near-miss correlation, and investigation workflows' },
      { standard: 'DOT Pipeline Safety', status: 'available', description: 'Pipeline inspection tracking and compliance documentation management' },
    ],
    trustTierDefaults: [
      { actionScope: 'grid.operations', maxTier: 'T0', rationale: 'Grid control actions observe only — human operator required for all changes' },
      { actionScope: 'generation.dispatch', maxTier: 'T1', rationale: 'Generation dispatch recommendations require operator confirmation' },
      { actionScope: 'field.dispatch', maxTier: 'T3', rationale: 'Field crew assignments are reversible and time-sensitive' },
      { actionScope: 'maintenance.scheduling', maxTier: 'T3', rationale: 'Maintenance window scheduling is reschedulable' },
      { actionScope: 'safety.reporting', maxTier: 'T2', rationale: 'Safety reports require safety officer review' },
      { actionScope: 'environmental.filing', maxTier: 'T2', rationale: 'Environmental filings require compliance review' },
      { actionScope: 'scada.interface', maxTier: 'T0', rationale: 'SCADA/OT systems are observe-only — no automated write access' },
      { actionScope: 'customer.communication', maxTier: 'T3', rationale: 'Customer outage notifications are standard and reversible' },
    ],
    shadowScenarios: [
      {
        title: 'Transformer Failure Predicted Late',
        problem: 'Distribution transformer with declining oil quality over 6 months, noticed only during scheduled inspection 2 weeks after failure. 4-hour outage, 3,200 customers affected.',
        detection: 'Asset Performance Monitor flags degradation trend at month 3 based on dissolved gas analysis.',
        action: 'Planned replacement scheduled during low-load period with pre-staged equipment.',
        savings: '$180K emergency replacement avoided vs $45K planned replacement',
      },
      {
        title: 'NERC CIP Audit Finding',
        problem: '3 access control gaps found because employee role changes not propagated to CIP systems within 24 hours.',
        detection: 'Regulatory Compliance Tracker flags access control discrepancies within 2 hours of role change.',
        action: 'Automated access review triggered on HR role changes with compliance officer notification.',
        savings: 'Risk avoided: $1M/day NERC penalty',
      },
      {
        title: 'Safety Near-Miss Pattern',
        problem: '7 near-miss reports involving same substation equipment over 4 months across 3 crews. Pattern connected only after injury occurred.',
        detection: 'Safety Incident Correlator identifies equipment-location pattern after 3rd near-miss report.',
        action: 'Equipment flagged for inspection, crews alerted, work procedures updated before injury.',
        savings: 'Injury prevented + equipment failure avoided',
      },
    ],
    estimatedMinutes: 35,
  },
];
