using ArchonAI.Core.Interfaces;
using ArchonAI.Core.Interfaces.Tooling;
using ArchonAI.Core.Models;
using ArchonAI.Core.Models.Tooling;
using CoreTask = ArchonAI.Core.Models.Task;

namespace ArchonAI.Agents.Tooling;

/// <summary>
/// Tool for calling internal platform services (planner/reasoner).
/// </summary>
public sealed class InternalServiceTool : IAgentTool
{
    private readonly IPlanner _planner;
    private readonly IReasoner _reasoner;

    public InternalServiceTool(IPlanner planner, IReasoner reasoner)
    {
        _planner = planner;
        _reasoner = reasoner;
    }

    public string Name => "internal.service";

    public async global::System.Threading.Tasks.Task<ToolExecutionResult> ExecuteAsync(ToolExecutionRequest request, CancellationToken cancellationToken = default)
    {
        request.Parameters.TryGetValue("action", out string? action);

        if (string.Equals(action, "plan", StringComparison.OrdinalIgnoreCase))
        {
            var objective = new Objective(
                Id: Guid.NewGuid(),
                Title: request.Parameters.GetValueOrDefault("title", "Tool Objective"),
                Description: request.Parameters.GetValueOrDefault("description", "Generated by tooling"),
                Constraints: new Dictionary<string, string>(),
                CreatedAtUtc: DateTimeOffset.UtcNow,
                DueAtUtc: null);

            IReadOnlyList<CoreTask> tasks = await _planner.CreatePlanAsync(objective, cancellationToken);
            return new ToolExecutionResult(Name, true, new Dictionary<string, string>
            {
                ["taskCount"] = tasks.Count.ToString()
            }, Array.Empty<string>(), DateTimeOffset.UtcNow);
        }

        if (string.Equals(action, "evaluate", StringComparison.OrdinalIgnoreCase))
        {
            var objective = new Objective(Guid.NewGuid(), "Evaluation objective", "Evaluate result", new Dictionary<string, string>(), DateTimeOffset.UtcNow, null);
            string feedback = await _reasoner.EvaluateAsync(objective, Array.Empty<ExecutionResult>(), cancellationToken);

            return new ToolExecutionResult(Name, true, new Dictionary<string, string>
            {
                ["feedback"] = feedback
            }, Array.Empty<string>(), DateTimeOffset.UtcNow);
        }

        return new ToolExecutionResult(Name, false, new Dictionary<string, string>(), new[] { "Unsupported internal service action." }, DateTimeOffset.UtcNow);
    }
}
