FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY ./archonai/ArchonAI.slnx ./
COPY ./archonai/src ./src

RUN dotnet restore ./ArchonAI.slnx
RUN dotnet publish ./src/ArchonAI.Worker.Scheduler/ArchonAI.Worker.Scheduler.csproj -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app

COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "ArchonAI.Worker.Scheduler.dll"]
