FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY ./archonai/ArchonAI.slnx ./
COPY ./archonai/src ./src

RUN dotnet restore ./src/ArchonAI.Worker.Scheduler/ArchonAI.Worker.Scheduler.csproj
RUN dotnet publish ./src/ArchonAI.Worker.Scheduler/ArchonAI.Worker.Scheduler.csproj -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime

RUN groupadd --gid 1654 archon && useradd --uid 1654 --gid archon --shell /bin/false --create-home archon

WORKDIR /app

COPY --from=build --chown=archon:archon /app/publish .
USER archon
ENTRYPOINT ["dotnet", "ArchonAI.Worker.Scheduler.dll"]
